version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/bart-ridership
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
