version: '3.1'

services:

  nginx:
    container_name: nginx
    restart: always
    build: ./bart_ridership/nginx
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    container_name: web
    restart: always
    build: ./bart_ridership/app
    environment:
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - ~/.aws:/root/.aws:ro
