version: '3'

services:
  db:
    image: postgres:11
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    image: bart-ridership:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8050:8050"
    command: bart/app.py


